[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/email_templates/*"]

[[scheduled]]
  name = "nightly-reminders"
  cron = "50 1 * * *"
  function = "nightlyReminders"

[[scheduled]]
  name = "nightly-vaccine-alerts"
  cron = "0 10 * * *"
  function = "nightlyVaccineAlerts"